---
title: "Coursera R Programming"
author: "Kevin Ostheimer"
date: "14.07.2014"
output: pdf_document
toc: yes
toc_depth: 2
---
#Basistypen
## vector()
```{r}
v_vec<-c(1:4,11:14); v_vec
v_vec_b<-seq(from = -pi, to = pi, length.out = 10); v_vec
```

## list()
```{r}
l_list<-list(ganzzahl=c(1:4), c("Hallo","Lala")); l_list
```

## matrix()
```{r}
m_mat<-matrix(v_vec, nrow=5, ncol=4); m_mat
dim(m_mat)
# Ändern der Dimension einer Matrix
dim(m_mat)<-c(10,2); m_mat

# Generierung aus zwei Vectoren
v1<-1:4
v2<-11.1:14.1
cbind(v1,v2)
rbind(v1,v2)
```

## factor()
```{r}
f_fac<-c("pos","neg","pos","pos","neg")
table(f_fac)
```

## data.frame()
```{r}
a <- c(10,20,15,43,76,41,25,46)                        # numerisch
b <- factor(c("m", "w", "m", "w", "m", "w", "m", "w")) # Faktor Geschlecht: m=männlich, w=weiblich
c <- c(2,5,8,3,6,1,5,6)                                # numerisch
myframe <- data.frame(a,b,c); 
names(myframe)<-c("Age","Gender","Dose"); myframe
```


## Missing values in a vector
```{r}
x<-c(1,2,NA,10)
good<-!is.na(x); good
y<-x[complete.cases(x)]; y
# Bei einer Matrix geht das so:
m<-matrix(rbinom(10,1,0.2),5,2)
m[3,1]<-NA
# Variante 1
m[complete.cases(m),]
# Variante 2
subset(m,subset = complete.cases(m),select = c(1,2))
```

## Daten I/O
Lesen eines komprimierten Formats, Mindestkonfiguration
```{r}
dat<-read.table(unz("rprog-data-quiz1_data.zip","hw1_data.csv"), sep = ",",header = TRUE,quote = "\"")
head(dat)
class(dat)
colnames(dat)
```

Abspeichern von Workspace Variablen
```{r}
```

Clear Workspace
```{r}
rm(list=ls())
```

## SingleData I/O
```{r}
dat<-airquality
dput(x = dat, file = "dat.R")
rm(list=ls())
dat<-dget(file = "dat.R")
```
dput, dget

## MultiData I/O
```{r}
v_vec<-c(1:4,11:14);
m_mat<-matrix(v_vec, nrow=4, ncol=4);
# Die Variablen müssen in Anführungszeichen
dump(c("v_vec","m_mat"),file = "dat.R")
source("dat.R")
ls()
```